Info: No gpu to set
Info: Operating System:  linux
Info: Tested for tf-gpu= 2.3 This tf version:  2.11.0
Info: Models implemented: ['mlp_eg', 'mlp_nac', 'mlp_nac2', 'mlp_e', 'mlp_g2']
Debug: starting training model energy_gradient
Run: /scratch/adaogomes.l/DBH/unsub/ML-NAMD/step2_grid_search/grid-search/NN-dbh-3_300_128_1e-08_1e-08_0.005/NN-dbh/energy_gradient Instance: 0 on GPU: -1 training
Run: /scratch/adaogomes.l/DBH/unsub/ML-NAMD/step2_grid_search/grid-search/NN-dbh-3_300_128_1e-08_1e-08_0.005/NN-dbh/energy_gradient Instance: 1 on GPU: -1 training
Debug: successfully started training for models energy_gradient
Fits submitted, waiting...
Seraching Folder for fitresult...
Info: Imported weights for: energy_gradient_v0
Info: Imported weights for: energy_gradient_v1
Info: Imported scaler for: energy_gradient_v0
Info: Imported scaler for: energy_gradient_v1
Debug: loaded all models.
